// <auto-generated />
using CidadesBrasileiras.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CidadesBrasileiras.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250628151759_add-municipios-estado")]
    partial class addmunicipiosestado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CidadesBrasileiras.Core.Models.Estado", b =>
                {
                    b.Property<int>("CodigoEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodigoEstado"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CodigoEstado");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("CidadesBrasileiras.Core.Models.Municipio", b =>
                {
                    b.Property<int>("CodigoMunicipio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CodigoMunicipio"));

                    b.Property<bool>("Capital")
                        .HasColumnType("boolean");

                    b.Property<int>("CodigoEstado")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Populacao")
                        .HasColumnType("integer");

                    b.HasKey("CodigoMunicipio");

                    b.HasIndex("CodigoEstado");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("CidadesBrasileiras.Core.Models.Municipio", b =>
                {
                    b.HasOne("CidadesBrasileiras.Core.Models.Estado", "Estado")
                        .WithMany("Municipios")
                        .HasForeignKey("CodigoEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("CidadesBrasileiras.Core.Models.Estado", b =>
                {
                    b.Navigation("Municipios");
                });
#pragma warning restore 612, 618
        }
    }
}
